version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_app
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dars2
    ports:
      - "5430:5432"
    volumes:
      - p_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_app
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: nest_dars2
    restart: always
    ports:
      - "3005:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start:prod
      "

volumes:
  p_data:
